title: Daniel Vernberg - Portfolio
email: daniel.vernberg@gmail.com
tagline: Nyutexaminerad webbutvecklare
description: >
  Daniel Vernberg Portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://danielv14.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
sass:
    style: compressed
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# Server Config options
livereload: true     # You no longer need to include --livereload

include: ['_pages']
exclude: ['README.md']

# Collections, for example portfolio/project items
collections:
  projects:
    output: true
    permalink: "/portfolio/:title"


# Set default attributes
defaults:
  -
    scope: # Setup of a scope
      path: ""
      type: "projects" # Target projects
    values:
      layout: "project" # Set default layout to project
