title: Daniel Vernberg - Portfolio
email: daniel.vernberg@gmail.com
tagline: Nyutexaminerad webbutvecklare
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github-url: github.com/danielv14
bio: >
  Jag heter Daniel och skapar webbplatser och webappar.
  När jag inte knackar kod eller lyssnar på podcasts om kod
  ser jag gärna en sci-fi film eller senaste avsnittet av Westworld.

# arrays for used technologies
tech-webdev: [HTML5, CSS3 & SCSS, Javascript, jQuery, Angular v1, Node, Laravel, Rest API, Ionic & Cordova, Vue.js, Bootstrap, Ruby on Rails, PHP]
tech-other: [MVC Metodik, Sketch, Git, Digital OCean, Python, PostgreSQL, MySQL, NoSQL, Gulp, Heroku]

# Build settings
markdown: kramdown
theme: minima
sass:
    style: compressed
gems:
  - jekyll-feed
  - jekyll-bootstrap-sass
exclude:
  - Gemfile
  - Gemfile.lock

# Server Config options
livereload: true     # You no longer need to include --livereload

include: ['_pages']
