title: Daniel Vernberg - Portfolio
email: daniel.vernberg@gmail.com
description: >
  Daniel Vernberg Portfolio. Utvecklare med fokus på webben.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://danielv14.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
sass:
    style: compressed
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - Rakefile
  - package.json
  - node_modules
  - gulpfile.js
  - _scripts
include: ['_pages']

# Server Config options
livereload: true     # You no longer need to include --livereload

# Collections, for example portfolio/project items
collections:
  projects:
    output: true
    permalink: "/portfolio/:title"
  posts:
    output: true
    permalink: "artikel/:title"


# Set default attributes
defaults:
  -
    scope: # Setup of a scope
      path: ""
      type: "projects" # Target projects
    values:
      layout: "project" # Set default layout to project
